# Copyright 2023 BerithFoundation
# SPDX-License-Identifier: LGPL-3.0-only

version: '1'
services:
  relayer1:
    build:
      context: .
    container_name: relayer_1
    command: --config /config/config.json --keystore=/keys --password=123 --latest
    volumes:
      - ./config:/config
      - ./keys:/keys/
  relayer2:
    build:
      context: .
    container_name: relayer_2
    command: --config /config/config.json --keystore=/keys --password=123 --latest
    volumes:
      - ./config:/config
      - ./keys:/keys/
